name:               foghorn-base
version:            0.1.0.0
language:           Haskell2010

author:             Robert Tumarkin
maintainer:         https://github.com/tumarkin

synopsis: Foundational types and constraints for the Foghorn DSL
description: |
  Foghorn.Base defines the core kind-level economic types (EconType),
  dataset indices (EconIndices), and associated constraints used across
  the Foghorn ecosystem. It provides the type-safe foundations for the
  Foghorn DSL, which supports declarative, replicable econometric
  research.  

  Most end users will not interact with this library directly, but will instead
  import domain-specific Foghorn modules that build on top of these base
  types. Foghorn.Base is intended for library authors, contributors, and those
  extending the DSL.
category: Econometrics, Language

license: "LicenseRef-PolyForm-Noncommercial-1.0.0"
license-file: LICENSE
copyright: (c) 2025 Rob Tumarkin

extra-source-files: CHANGELOG.md
# bug-reports:
 
library:
  source-dirs: src

dependencies:
  - base >=4.20.0.0 && <4.21
  - singletons ^>= 3.0.4
  - singletons-base ^>= 3.4
  - singletons-th ^>= 3.4
  - template-haskell ^>= 2.22.0.0

default-extensions:
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - OverloadedRecordDot
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns
